improve: add trailing icon to combobox and select
prisma/lens pull request #289
Opened 2021-09-08 07:11 UTC by eemmiillyy

2021-09-08 08:10 UTC, madebysid commented on src/components/combo-box/ComboBox.tsx
> +    trailing?: boolean
I don't think this `trailing` prop makes sense here because it is not obvious that this is about the icon. There's nothing tying the two together.

In general I'm skeptical of the idea that there should be slots for two icons (leading, for Heroku, Planetscale tec., and trailing for this lock), are we sure about this? Have we thought this through?

I think we should just use the existing `icon` prop (AKA close this PR) for the lock icon as well. If Juli does indeed want two icons, then I suppose we should rename the props to `leadingIcon` and `trailingIcon`.

2021-09-08 08:14 UTC, madebysid commented on src/components/combo-box/ComboBox.tsx
> +    trailing?: boolean
To repeat myself, we _have_ to be very careful extending any API surface so that we can keep this design system a design system (opinionated) and not just a set of components that can be endlessly customized.

This should be as much of a limitation for designers as it is for developers.

Tagging @julietacurdi for thoughts. Do we want slots for two icons in the `ComboBox`? (and by extension, `Select`)

2021-09-08 15:54 UTC, madebysid commented on src/components/combo-box/ComboBox.tsx
> +    trailing?: boolean
Talking to Juli, it seems there are real use cases for two icon slots, so let's split the `icon` prop int to `leadingIcon` and `trailingIcon` (make changes in Cloud when you bump up the version).

Can you also add a story that shows what happens when the text is too long? You might have to handle text truncation (which I believe isn't handled right now)

2021-09-08 15:56 UTC, julietacurdi commented on src/components/combo-box/ComboBox.tsx
> +    trailing?: boolean
Definitely we will need truncation of the repo name. 3 dots and maintain the spacing to the icon. Let me know if you need design, its pretty straight forward

2021-09-09 13:03 UTC, luanvdw commented
How do we want to treat trailing icons in the input,

When selecting an Item with a leading icon it also shows the icon in the input;

https://user-images.githubusercontent.com/6928171/132689270-571d47ff-3b4c-4d24-9529-19bd8988caf5.mp4

When selecting a trailing icon it does not;

https://user-images.githubusercontent.com/6928171/132689320-7d7b8569-73e5-42b1-8c40-b76e35fe3293.mp4

Not rendering a trailing Icon in the input is probably more clean and less cluttered and makes sense in the context of private vs public with the lock icon or do we want to add specific logic such that if it is only a trailing icon then we do want to show it and if it is both then we only want to show the leading icon?

@julietacurdi wdyt?

2021-09-13 07:18 UTC, eemmiillyy commented
<img width="1393" alt="Screenshot 2021-09-13 at 09 07 23" src="https://user-images.githubusercontent.com/55739812/133040275-3ccee72d-460d-4e52-9884-668e5c724bae.png">

I added truncation but the dropdown width changes according to the input (which expands to accomodate the full title) so anything past 25 characters looks like this which I find a bit weird.

2021-09-13 07:30 UTC, eemmiillyy commented
<img width="1384" alt="Screenshot 2021-09-13 at 09 28 25" src="https://user-images.githubusercontent.com/55739812/133041772-41c96428-b388-4259-96ef-2eb38ebc4fdc.png">


I'm truncating after 50 characters but since the input accommodates the whole text and can be any width this "early" truncation will happen. Are we sure this is necessary? I think it actually looked fine always showing the full repo name: 
<img width="410" alt="Screenshot 2021-09-13 at 09 29 41" src="https://user-images.githubusercontent.com/55739812/133041950-b1dd0b7d-c263-406f-9c19-e59849737d08.png">
(From the original ticket)

2021-09-13 11:43 UTC, madebysid commented on src/components/combo-box/ComboBox.stories.tsx
> +  </ComboBox.Container>
Can you change this story to better reflect when a `leadingIcon` is used for real in Cloud?

Generally, I keep stories accurate to usage. There are no instances where locks render as leading icons. Let's replace locks with the org logo / user profile picture, just like they will be used on Cloud.

2021-09-13 11:46 UTC, madebysid commented on src/components/combo-box/ComboBox.stories.tsx
> +    <ComboBox.Option key="docs" trailingIcon="lock">
Here too, think of something more realistic. If you _have_ to use repo names, keep the text real data (so `prisma/longreponamesomethingliekthis` instead of `prisma/prisma/prisma/prisma/prisma`.

Alternatively, you could use something else

2021-09-13 11:47 UTC, madebysid commented on src/components/combo-box/ComboBox.stories.tsx
> +          leadingIcon="lock"
I thought locks were going to be a trailing icon?

Same comment here too I guess, keep stories realistic. It will help visualize what components will actaully look like, and avoid the design system from becoming a set of components that can be customized.

2021-09-13 11:48 UTC, madebysid commented on src/components/combo-box/ComboBox.stories.tsx
> +    <ComboBox.Option key="railway" leadingIcon="railway">
This is realistic. since on Cloud, brand icons show up as `leadingIcon`s!

2021-09-13 11:49 UTC, madebysid commented on src/components/combo-box/ComboBox.tsx
> +              <Icon name={state.selectedItem.props.leadingIcon} size="sm" />
Do we not want trailing icons to also show up in the "selected" item?

2021-09-13 11:51 UTC, madebysid commented on src/components/internal/ListBox.tsx
> +  /** Whether the icon should be placed before the title or after it */
This description is not accurate. This prop does not control where the icon is placed, it is `An icon to show before the title`.

Also update the description for `leadingIcon`.

Also make sure you change this everywhere else this might have been copied & pasted.

2021-09-13 11:51 UTC, madebysid commented on src/components/internal/ListBox.tsx
> +            : (option.rendered as string).substring(0, 50) + "..."}
Why JS? Use CSS overflow ellipsis.

2021-09-13 11:52 UTC, madebysid commented on src/components/select/Select.stories.tsx
> +      prisma/prisma/prisma/prisma/prisma/prisma/prisma/prisma/
Here too, keep this story realistic. Either rename the repo names to be long, or use something else (aka not repo selector)

2021-09-13 11:52 UTC, madebysid commented on src/components/select/Select.tsx
> +                <Icon name={state.selectedItem.props.leadingIcon} size="sm" />
Same, do we not want trailing icons to show up on the "selected" item?

2021-09-13 11:52 UTC, madebysid requested changes
Left a few comments

2021-09-13 11:57 UTC, madebysid commented
@luanvdw I think the trailing icon not showing up is a bug. Remember that trailing icons are not going to be used **just** for repos, in some contexts, it  might be weird that trailing icons do not show up in the "selected" item. IMO the selected item should look exac tly like the options.

@eemmiillyy Same, remember that a `Select` is not used only for repo selection (although that be the case _right now_, don't make decisions assuming that that will always be the case. Also, why can't we truncate with CSS? You might need an extra `<span>` or something, but I'm pretty sure it should be possible. If we're worried about truncation hiding important details, then make sure that multi-line options render correctly & icons are aligned correctly. Make sure to add a story for it so it gets "tested"

2021-09-13 13:10 UTC, eemmiillyy commented on src/components/combo-box/ComboBox.stories.tsx
> +    <ComboBox.Option key="railway" leadingIcon="railway">
This case already covers the WithIcon's case so I'll remove it.

2021-09-13 13:11 UTC, eemmiillyy commented on src/components/combo-box/ComboBox.tsx
> +              <Icon name={state.selectedItem.props.leadingIcon} size="sm" />
Juli said it didn't matter but I'll add them just be consistent with leadingIcons.

2021-09-13 14:05 UTC, eemmiillyy commented
Made the changes, this is what multiline no truncation looks like. 

<img width="1319" alt="Screenshot 2021-09-13 at 16 02 54" src="https://user-images.githubusercontent.com/55739812/133097819-90f9dece-36fc-4002-99f6-653df03f6a4b.png">

Could someone help me the with CSS please? This is what adding the trailing icon to the input in the combobox looks like. It keeps too far to the right. Select is fine. 
This looks misleading, like you can't change the dropdown, so it should be right beside the title. I can't get the CSS right, anyone want to take a stab at it? Thanks in advance 🙏 
<img width="1308" alt="Screenshot 2021-09-13 at 16 04 25" src="https://user-images.githubusercontent.com/55739812/133098075-1ad69e01-2bd6-4ad2-aa0e-dc738e0db986.png">

2021-09-21 08:28 UTC, madebysid approved these changes
I guess if Juli is okay with removing the icon after selection, then this can be merged in

2021-09-21 08:32 UTC, eemmiillyy commented
> I guess if Juli is okay with removing the icon after selection, then this can be merged in

Yes @luanvdw confirmed with her yesterday :)

2021-09-21 08:53 UTC, madebysid commented
@luanvdw if you could go through this as well, we can merge it! (In fact, merge it once you see this)

2021-09-21 10:48 UTC, luanvdw approved these changes

2021-09-21 10:49 UTC, merged