improve: add static footer and scrollable menu contents
prisma/lens pull request #293
Opened 2021-09-15 12:12 UTC by ruheni

closes https://github.com/prisma/cloud/issues/499

2021-09-16 12:53 UTC, luanvdw commented on src/components/internal/ListBox.tsx
> +              style={{ maxHeight: "350px" }}
This max Height is being applied to all instances and not just in the case for when we have a footer. Probably a good thing to limit the overall height of the dropdown in any case (to place some restriction on the impact that a long list can have on ux)

Just mentioning it to make sure we know the outcome we want.

![static_list](https://user-images.githubusercontent.com/6928171/133615409-3f92a137-018d-4f6e-92ce-45e1dd968959.png)

2021-09-16 12:55 UTC, luanvdw commented on src/components/combo-box/ComboBox.stories.tsx
> +export const WithFixedMenuHeightFooter = () => (
Since the menu height is not controlled by a prop, we should probably rename this to something more generic, representing an example of a long list like, `WithALotOfItems`

2021-09-16 12:58 UTC, luanvdw commented on src/components/combo-box/ComboBox.stories.tsx
> +      Can't find ye repository?
StreetCred += 1 for thuglife grammer 😎

2021-09-16 13:14 UTC, ruheni commented on src/components/combo-box/ComboBox.stories.tsx
> +      Can't find ye repository?
This was already there, I copied it from the other stories 😅

2021-09-16 13:25 UTC, luanvdw approved these changes
LGTM :) 

We just need to make sure about the behaviour we want with restricting the height for all drop-downs. IMO I am for it, it seems sound to have some sort of limit on the height of a list given a large amount of items to display.

In the event of content over flowing it would be nice if the overflow is against the divider, the <Divider /> component at the end that we use within the footer has a margin on it that makes the content "disappear" before the line.

![overflow](https://user-images.githubusercontent.com/6928171/133620314-ce0fc0a2-3120-4fdf-89b0-a1f752fb4662.png)

2021-09-17 08:33 UTC, madebysid requested changes
One small change

2021-09-17 08:33 UTC, madebysid commented on src/components/combo-box/ComboBox.stories.tsx
> +      Can't find ye repository?
Lol this must be my doing then, can you fix it pls

2021-09-17 08:33 UTC, madebysid commented on src/components/internal/ListBox.tsx
> +              style={{ maxHeight: "350px" }}
The text being cut straight off looks weird.

Instead of the current padding top + bottom of the list box container, add a margin top on the first list item, and a margin bottom on the last one, so that it looks the same as it does right now, but instead of seeing a visible line cutting off the text, it will be cut off by the list box container, which will look more natural.

2021-09-17 11:35 UTC, madebysid commented on src/components/combo-box/ComboBox.stories.tsx
> +      Can't find yet repository?
*your

2021-09-17 13:17 UTC, ruheni commented on src/components/internal/ListBox.tsx
> +              style={{ maxHeight: "350px" }}
Do you mean this? I've added a margin to the first and last items on the list
<img width="300" alt="Screenshot 2021-09-17 at 16 16 13" src="https://user-images.githubusercontent.com/33921841/133788733-504b4e88-9516-425e-9337-22a5fbdd2cdc.png">

2021-09-20 08:51 UTC, madebysid commented on src/lib.css
> +}
Let's not make this a habit.

The `.menu` and `.input` are custom classes because they are very common and use a lot of classes to look right. If we start creating classes for every group of Tailwind classes, it'll be just like using CSS (but more convoluted).

Add these classes directly to the `ListBoxOption`

2021-09-20 08:54 UTC, madebysid commented
@ruheni There's still an invisible line cutting the text off though: 
![Screen Shot 2021-09-20 at 10 52 10](https://user-images.githubusercontent.com/7689783/133977409-5f2c1358-a817-473c-9e30-4090c3312e83.png)

And also, look at stories you didn't change, the margins on the top and bottom are different now (bottom is larger):
![Screen Shot 2021-09-20 at 10 52 23](https://user-images.githubusercontent.com/7689783/133977520-c3bcc5c2-1f52-426d-b6b6-cf89cfcfbe40.png)

I don't think you removed the padding from the menu container, so there's "double padding" on the bottom.

2021-09-20 13:18 UTC, ruheni commented
I've resolved the Invisible line - removed the padding around it. 

What do you mean by the padding from the menu container? I removed the padding that was in the `.menu` class. The margins and padding seem to be even for the list option 🤔
<img width="576" alt="Screenshot 2021-09-20 at 16 16 50" src="https://user-images.githubusercontent.com/33921841/134008861-eeedbd5f-6084-4b3f-ada4-dfc3de9b7dbf.png">

<img width="611" alt="Screenshot 2021-09-20 at 16 16 33" src="https://user-images.githubusercontent.com/33921841/134008838-643d8cac-c1f0-424d-84b8-dbbc5f22338b.png">

2021-09-21 11:17 UTC, madebysid approved these changes

2021-09-21 11:20 UTC, madebysid commented on src/components/separator/Separator.tsx
> +        "border-b": orientation === "horizontal",
Why was this changed?

2021-09-21 11:25 UTC, madebysid commented
@luanvdw FYI there is a website header diff on Chromatic in this PR. It looks like the header story was depending on `lib.css` in some way, and changing the styles of the `.menu` class affected it as well. Not sure where the website header actually gets its styles (I can see styled-components, but also global CSS classes in the form on `className=""`).

I'm accepting the diff for now, but be careful when updating lens on there whenever you do.

2021-09-21 11:27 UTC, merged

2021-09-21 11:38 UTC, ruheni commented on src/components/separator/Separator.tsx
> +        "border-b": orientation === "horizontal",
This was causing the invisible white line cutting off the text in the footer

2021-09-21 12:49 UTC, ruheni commented
We could either create a new Separator and remove the top padding or modify the component directly given that I haven't seen it in use in other components. WDYT?
 
![Screenshot 2021-09-21 at 15 47 34](https://user-images.githubusercontent.com/33921841/134173106-8986a382-abb5-4560-beb7-16c326ac9599.png)

2021-09-21 13:13 UTC, madebysid commented
Oh that's what the separation was? Then yeah, my mistake. I'll remove the margin around the separator again.