(WIP) Migrating website-v9 header to lens
prisma/lens pull request #410
Opened 2022-07-14 14:28 UTC by carlagn

## Describe this PR

Website-v9 has the most recent version of the header, implemented using `@emotion/styled` and `@emotion/react` for the styled components. The goal of this PR is to migrate these components from website-v9 to lens design system, so every webpage under prisma (includes: blog, docs, homepage, website, etc) has the same header in order to keep consistency.

This will also hopefully handle the issues of the [navbar jumping](https://github.com/prisma/website-v9/issues/59), as the re-render of a slightly different component (implementation-wise) may be causing the visual flickering on pages that use the header from `lens` (i.e. /docs)

## Changes

- Removed `styled-components` package.
- Added `"@emotion/babel-preset-css-prop"` to storybook presets.
- Added the following packages:
  - "@emotion/core": "^11.0.0",
  - "@emotion/react": "^11.9.0",
  - "@emotion/styled": "^11.9.3"
- Added `<ThemeProvider />` to `LensWebProvider`. This should only influence the web components from lens.
- Deleted unused/old/deprecated files (i.e. `Dropdown`, `Navbar`, etc), in favor of new versions from `website-v9`, as well as replaced the `theme` value primitives and styling objects (for dark + default).

## What issue does this fix?

[Fixes website-v9#62](https://github.com/prisma/website-v9/issues/62)

## Any other relevant information

`<ThemeProviders />` is seemingly not working, `theme` property is provided straight from the import, as it seems it is a recurring issue to use styled components together with storybook due to version incompatibilities. This is likely the main reason why this PR is still deemed as a `WIP`.

2022-07-29 10:33 UTC, tatianainama requested changes
For this review, I focused mainly in changes that have an impact on PDP Control Plane

---


We are getting inferred types in every component as `Emotion.JSXElement`.
I think this is caused by the new configs introduced in `tsconfig.json` 

![image](https://user-images.githubusercontent.com/8246284/181738743-9f461aff-1890-4b50-ab69-1c6affb0c839.png)

Declaring types fixes this

```jsx
const PickerContainer:FC<PickerProps> = ({ ... }) => { ... }
```

![image](https://user-images.githubusercontent.com/8246284/181739370-fc7a4c62-d849-4276-9095-0885fea67d10.png)

2022-07-29 10:33 UTC, tatianainama commented on src/components/combo-box/ComboBox.tsx
> +export const ComboBox: any = {
Same as before

2022-07-29 10:36 UTC, tatianainama commented on src/components/menu/Menu.tsx
> +export const Menu: any = {
Same as https://github.com/prisma/lens/pull/410#discussion_r933044403

2022-07-29 10:37 UTC, tatianainama commented on src/components/select/Select.tsx
> +export const Select: any = {
Same as https://github.com/prisma/lens/pull/410#discussion_r933044403

2022-07-29 12:09 UTC, carlagn commented on src/components/combo-box/ComboBox.tsx
> -    id,
Having this variable results in this build error: 
```
[!] semantic error TS2345: Argument of type '{ id: string | undefined; autoFocus: boolean | undefined; children: CollectionChildren<ComboBoxOption<OptionKey>>; allowsEmptyCollection: true; ... 9 more ...; onSelectionChange: (k: Key) => void; }' is not assignable to parameter of type 'ComboBoxStateProps<ComboBoxOption<OptionKey>>'.
  Object literal may only specify known properties, and 'id' does not exist in type 'ComboBoxStateProps<ComboBoxOption<OptionKey>>'.
```

any clue on its origin? Reading the docs on react-stately I can't find any variable for `id` or similar, I might be missing something?

2022-07-29 13:00 UTC, carlagn commented on src/cloud/picker/Picker.tsx
> +export const Picker: any = {
The inference does not seem to be posing a problem for the build, so I'll revert it back

2022-08-02 10:56 UTC, tatianainama commented on src/components/combo-box/ComboBox.tsx
> -    id,
After some investigation, I realised this `id` shouldn't be passed here (as the error we are getting from TS hints 😓).
The `id` is later passed as its own prop to the `ListBoxOverlay` component, so we are good removing it, sorry for the confusion!

2022-08-02 12:28 UTC, tatianainama commented on src/cloud/picker/Picker.tsx
> +export const Picker: any = {
Uhm, I tested the new changes locally, and I'm still getting the following when building:

```
[!] (plugin rpt2) Error: lens/src/components/combo-box/ComboBox.tsx(225,14): semantic error TS2742: The inferred type of 'ComboBox' cannot be named without a reference to '@react-types/overlays/node_modules/@react-types/shared'. This is likely not portable. A type annotation is necessary.
```

Can we try again after applying the changes from https://github.com/prisma/lens/pull/410#discussion_r935418826 ?

2022-08-03 11:01 UTC, carlagn commented on src/cloud/picker/Picker.tsx
> +export const Picker: any = {
[#410 (comment](https://github.com/prisma/lens/pull/410#discussion_r935418826) doesn't fix.

Build error is still the same as yours. Setting type as `Object` i.e.

```js
export const Picker: Object = {
```

works but might not be specific enough.

2022-08-09 09:41 UTC, carlagn commented on src/cloud/picker/Picker.tsx
> +export const Picker: any = {
@tatianainama any thoughts on this fix? :/ ^

2022-08-09 10:34 UTC, tatianainama commented on src/cloud/picker/Picker.tsx
> +export const Picker: any = {
After the upgrades, the error is gone 🎉

2022-08-09 10:50 UTC, tatianainama approved these changes
As I stated before, I focused mainly in changes that have an impact on PDP Control Plane, someone from Marketing team should take look at the changes this PR implies for the website.

Said that, everything looks good 😄

2022-08-09 12:29 UTC, merged