feat: Introduce Accordion component
prisma/lens pull request #454
Opened 2022-09-12 12:54 UTC by tatianainama

Closes CP-2571

I initially started this component using [@react-aria's accordion](https://github.com/adobe/react-spectrum/tree/main/packages/%40react-aria/accordion) hooks, but it's still in alpha and ran into some issues, like https://github.com/adobe/react-spectrum/issues/1989; so I ended up building it from scratch.

I've also made some changes in `Checkbox` component, like improving paddings/margins and allowing JSX elements to match up with design requirements.

2022-09-12 15:12 UTC, sampolahtinen requested changes
All the comments are just optional change requests.

However, I would like us to focus on UI shift behavior when closing or opening accordion. As a comparison, [Chakra accordion](https://chakra-ui.com/docs/components/accordion) does not have such a shift. Some videos below!

Lens/Accordion:
https://user-images.githubusercontent.com/19226286/189690388-543bb279-4a1c-4a91-95a5-749483842ce1.mp4

Chakra:
https://user-images.githubusercontent.com/19226286/189690474-5a74b7a3-69f3-4948-af61-7b7a79dbce6d.mp4

2022-09-12 16:43 UTC, tatianainama commented on src/components/accordion/Accordion.tsx
> +  regionId?: string
Aside from testing, I'm thinking using this could be helpful for tracking purposes too (don't think we have that implemented for any type of element, but could be useful in the future)

2022-09-12 16:44 UTC, tatianainama commented on src/components/accordion/Accordion.tsx
> +            {variant && variant === "negative" ? (
Sounds like a great improvement 🙂

2022-09-12 16:50 UTC, tatianainama commented
> However, I would like us to focus on UI shift behavior when closing or opening accordion. As a comparison, [Chakra accordion](https://chakra-ui.com/docs/components/accordion) does not have such a shift. Some videos below!

That's a great point,  I've also noticed I completely missed adding transitions to this too (that was part of the requirements of the task too 😓)
I'll work on that, thanks for the feedback 🙏

2022-09-12 16:54 UTC, tatianainama commented on tailwind.config.js
> +      boxShadow: {
Not so sure about this one, what does the `disabled` class will define?

`disabled` status is represented in different ways based on the component (different color shades, shadows, icons, etc) so I don't think we could create a global `disabled` one 🤔

2022-09-13 08:01 UTC, sampolahtinen commented on tailwind.config.js
> +      boxShadow: {
That is a good point. Often times disabled class is a combination of `color, opacity` and possibly something else. So yes maybe it does not make sense to abstract it.

I was thinking about a situation where I have few times had to investigate how similar element's disabled state looks in terms of tailwind classes and then copy those to the element im working on. Was trying find a solution for such a case!

2022-09-13 09:15 UTC, tatianainama commented on src/components/accordion/Accordion.tsx
> +  const buttonId = `${accordionId}-button`
@sampolahtinen let me know what you think about this solution!

2022-09-13 10:34 UTC, tatianainama commented
@sampolahtinen I added some animations to the accordion now, let me know what you think!

About the shifting issue, I noticed it was caused by storybook's default layout settings (`flex` display + vertical alignment was creating the shifting) so I reset those settings for this specific story

2022-09-13 15:45 UTC, sampolahtinen commented on src/components/accordion/Accordion.tsx
> +            "max-h-screen transition-all duration-300": expanded,
Works great and now UI Shrink any longer! 🚀 

Following is a note, not a change request:
Let's just be aware of that animating `max-height` causes a reflow and it might provide a stuttering animation if the children is a heavy construction of elements. In case we ever encounter this, we can look into animating using `translate` property. However, animating translate and simultaneously pushing content down, becomes a bit annoying. Thus, lets just leave it for the future in case we need it!

2022-09-13 16:09 UTC, tatianainama commented on src/components/accordion/Accordion.tsx
> +  const buttonId = `${accordionId}-button`
> Its a minor cosmetic, but when writing tests or doing any kind of dom targeting, and you pass id to a component, you would expect that this is attached to the "main" element that provides the functionality - in this case a button that opens accordion.

That makes sense, I was considering the `div` container as the "main" element, but in reality, the button is the one making all the state changes, pushing updates!

2022-09-13 16:15 UTC, sampolahtinen commented on src/components/accordion/Accordion.tsx
> +      id: buttonId,
Just leaving a FYI for @luanvdw  here.

I noticed again that when using a hook from react-aria, that when passing `id` as an argument to the hook, the `id` wont be passed to the actual component when spreading `buttonProps`. Thus, we directly pass `id` on line 96.

This behavior probably occurs because a mismatch in different aria packages. This is not a major thing for now, just something to be aware of!

2022-09-13 16:15 UTC, sampolahtinen commented on src/components/accordion/Accordion.tsx
> +  const buttonId = `${accordionId}-button`
Looks great :)!

2022-09-13 16:17 UTC, sampolahtinen approved these changes
Thank you for the changes and great work with the VariantIcon component!

2022-09-13 16:33 UTC, tatianainama commented on src/components/accordion/Accordion.tsx
> +            "max-h-screen transition-all duration-300": expanded,
I think it goes against the idea of accordions to have complex elements inside: we want to avoid using them for critical and required steps, so I don't think we will have a problem here 🤔 

On a side note, I'm not so sure about the translate property here: you'll end up creating a bunch of layers to simulate the same effect (scale, opacity, positioning, etc) and transition layers can easily take a lot of resources. I'm all about using CSS for hardware acceleration, but I'm also skeptical of adding multiple of them if it's not necessary.

For this, I think it will be one of the cases where `will-change` property can be useful 😄

btw loving all the discussion here 🤓!

2022-09-14 12:32 UTC, merged